In [1]:
import requests as re
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup as bs
from selenium import webdriver as wd

In [2]:
url_poverty_rate="https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_poverty_rate"
url_unemployement_rate="https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_unemployment_rate"
url_fertility_rate="https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_fertility_rate"

In [3]:
headers={'Brave':'Client'}

In [4]:
web=wd.Chrome()

In [17]:
url_gdp="https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_GDP"
web=wd.Chrome()
web.get(url_gdp)
content=bs(web.page_source,'html.parser')
tables = content.find_all('table', class_='wikitable')
gdp_22_23=[]
table_heading_22_23=[]
table_index=0
if len(tables)>table_index:
    gdp_22_23_table=tables[table_index]
else:
    print("can't fine the specific table mentioned")
for i in gdp_22_23_table.find_all('th'):
    table_heading_22_23.append(i.text.strip())
for i in gdp_22_23_table.find_all('td'):
    cleaned_data=i.text.replace('\u202f*','').strip()
    gdp_22_23.append(cleaned_data)
gdp_22_23
gdp_22_23_data={}
for i in range(len(table_heading_22_23)):
    gdp_22_23_data[table_heading_22_23[i]]=gdp_22_23[i::3]
gdp_22_23_data
gdp_22_23=pd.DataFrame(gdp_22_23_data)
print(gdp_22_23.head())
web.quit()

  State/union territory GSDP (₹ millions) GSDP (US$ billions)
0           Maharashtra      31,080,218.7               417.2
1            Tamil Nadu      20,712,861.6               278.0
2               Gujarat      19,770,664.6               265.4
3         Uttar Pradesh      19,745,315.5               265.1
4             Karnataka      19,627,254.2               263.5

In [22]:
table_heading_22_23
gdp_22_23_data

          State/union territory GSDP (₹ millions) GSDP (US$ billions)
0                   Maharashtra      31,080,218.7               417.2
1                    Tamil Nadu      20,712,861.6               278.0
2                       Gujarat      19,770,664.6               265.4
3                 Uttar Pradesh      19,745,315.5               265.1
4                     Karnataka      19,627,254.2               263.5
5                   West Bengal      13,639,258.6               183.1
6                     Rajasthan      12,181,934.5               163.5
7                Madhya Pradesh      11,361,371.9               152.5
8                Andhra Pradesh      11,338,365.0               152.2
9                     Telangana      11,289,072.4               151.5
10                       Kerala       9,324,699.6               125.2
11                        Delhi       9,046,420.4               121.4
12                      Haryana       8,706,645.3               116.9
13                       Odisha       6,708,812.3                90.1
14                        Bihar       6,503,024.3                87.3
15                       Punjab       6,142,267.6                82.4
16                        Assam       4,126,118.7                55.4
17                 Chhattisgarh       4,064,158.2                54.6
18                    Jharkhand       3,588,625.9                48.1
19                  Uttarakhand       2,721,594.8                36.5
20            Jammu and Kashmir       1,999,174.2                26.8
21             Himachal Pradesh       1,762,694.7                23.7
22                          Goa         826,037.0                11.1
23                      Tripura         625,504.4                 8.4
24                   Chandigarh         456,352.6                 6.1
25                   Puducherry         442,378.6                 5.9
26                    Meghalaya         387,847.0                 5.2
27                       Sikkim         375,574.0                 5.0
28                      Manipur         365,944.7                 4.9
29            Arunachal Pradesh         351,235.4                 4.7
30                     Nagaland         319,125.4                 4.3
31                      Mizoram         278,235.0                 3.7
32  Andaman and Nicobar Islands         103,705.2                 1.5

In [6]:
url_gdp="https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_GDP"
web=wd.Chrome()
web.get(url_gdp)
content=bs(web.page_source,'html.parser')
tables = content.find_all('table', class_='wikitable')
table_data=[]
table_heading=[]
table={}
table_index=2
if len(tables) > table_index:
    specific_table = tables[table_index]
else:
    print(f"There are only {len(tables)} tables on the page.")
for i in specific_table.find_all('th'):
    table_heading.append(i.text.strip())
for i in specific_table.find_all('td'):
    table_data.append(i.text.strip())
statename=[]
for i in table_data:
    cleaneddata=i.replace('\u202f*','')
    statename.append(cleaneddata)
years=table_heading[0:13]
for i in range(len(years)):
    table[years[i]]=statename[i::13]
gdp_decade=pd.DataFrame(table)
print(gdp_decade.head())
web.quit()

  State/union territory    2011–12    2012–13    2013–14    2014–15  \
0        Andhra Pradesh  3,794,020  4,114,040  4,642,720  5,249,760
1     Arunachal Pradesh    110,630    125,470    145,810    179,590
2                 Assam  1,431,750  1,568,640  1,777,450  1,957,230
3                 Bihar  2,471,440  2,823,680  3,171,010  3,429,510
4          Chhattisgarh  1,580,740  1,775,110  2,068,330  2,211,180

     2015–16    2016–17    2017–18    2018–19    2019–20    2020–21  \
0  6,042,290  6,844,160  7,861,350  8,737,210  9,258,390  9,567,880
1    185,090    199,020    224,750    253,350    300,240    305,480
2  2,279,590  2,543,820  2,831,650  3,093,360  3,468,510  3,536,050
3  3,716,020  4,210,520  4,687,460  5,279,760  5,818,550  5,672,630
4  2,251,630  2,628,020  2,827,370  3,271,070  3,446,480  3,477,520

      2021–22     2022–23
0  11,338,370  13,177,280
1     351,240           –
2   4,126,120   4,931,670
3   6,503,020   7,513,960
4   4,064,160   4,576,080

In [8]:
url_litracy_rate="https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate"
web=wd.Chrome()
web.get(url_litracy_rate)
content=bs(web.page_source,'html.parser')
tables=content.find_all('table', class_='wikitable')
litracy_data=[]
litracy_heading=[]
table_index=0
litracy_data_dict={}
specific_table=tables[table_index]
for i in specific_table.find_all('td'):
    litracy_data.append(i.text.strip())
litracy_data=litracy_data[7::]
for i in specific_table.find_all('th'):
    litracy_heading.append(i.text.strip())
litracy_heading.remove('Census 2011[2]')
litracy_heading.remove('NSO survey (2017)[3]')
litracy_heading[4]='N_AVERAGE'
litracy_heading[5]='M_AVERAGE'
litracy_heading[6]='F_AVERAGE'
litracy_data.insert(219,'None')
litracy_data.insert(220,'None')
for i in range(len(litracy_heading)):
    litracy_data_dict[litracy_heading[i]]=litracy_data[i::7]
litracy_rate=pd.DataFrame(litracy_data_dict)
print(litracy_rate.head())
web.quit()

                        State or UT Average   Male Female N_AVERAGE M_AVERAGE  \
0  A&N islands[UT][citation needed]   86.63  90.27  82.43     86.27     90.11
1                 Andhra Pradesh[a]   67.02  74.88  59.15      66.9        80
2                 Arunachal Pradesh   65.38  72.55  57.70     66.95      73.4
3                             Assam   72.19  77.85  66.27      85.9      90.1
4                             Bihar   61.80  71.20  51.50      70.9      79.7

  F_AVERAGE
0     81.84
1      59.5
2     59.50
3      81.2
4      60.5

In [9]:
url_unemployement_rate="https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_unemployment_rate"
web=wd.Chrome()
web.get(url_unemployement_rate)
content=bs(web.page_source,'html.parser')
tables = content.find_all('table', class_='wikitable')
unemployement_data=[]
unemployement_heding=[]
unemployement_data_dict={}
table_index=0
if len(tables) > table_index:
    specific_table = tables[table_index]
else:
    print('table index not found')
for i in specific_table.find_all('th'):
    unemployement_heding.append(i.text.strip())
for i in specific_table.find_all('td'):
    unemployement_data.append(i.text.strip())
for i in range(len(unemployement_heding)):
    unemployement_data_dict[unemployement_heding[i]]=unemployement_data[i::2]
unemployement_rate=pd.DataFrame(unemployement_data_dict)
print(unemployement_rate.head())
web.quit()

  State or union territory Unemployment rate (%)
0           Andhra Pradesh                   4.8
1        Arunachal Pradesh                  18.3
2                    Assam                   0.4
3                    Bihar                  11.4
4             Chhattisgarh                   0.1

In [10]:
url_abbrevation="https://en.wikipedia.org/wiki/ISO_3166-2:IN"
web=wd.Chrome()
web.get(url_abbrevation)
content=bs(web.page_source,'html.parser')
tables = content.find_all('table', class_='wikitable')
abbrevation_data=[]
abbrevation_heading=[]
abbrevation_data_dict={}
table_index=0
if len(tables) > table_index:
    specific_table = tables[table_index]
else:
    print('table index not found')
for i in specific_table.find_all('th'):
    abbrevation_heading.append(i.text.strip())
for i in specific_table.find_all('td'):
    abbrevation_data.append(i.text.strip())
for i in range(0,2):
    abbrevation_data_dict[abbrevation_heading[i]]=abbrevation_data[i::4]
abbrevations=pd.DataFrame(abbrevation_data_dict)
print(abbrevations.head())
web.quit()

    Code Subdivision name (en)(Indian System of Transliteration)
0  IN-AN                        Andaman and Nicobar Islands
1  IN-AP                                     Andhra Pradesh
2  IN-AR                                  Arunāchal Pradesh
3  IN-AS                                              Assam
4  IN-BR                                              Bihār

In [11]:
url_exports="https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_exports"
web=wd.Chrome()
web.get(url_exports)
content=bs(web.page_source,'html.parser')
tables=content.find_all('table', class_='wikitable')
exports_data=[]
exports_heading=[]
export_data_dict={}
table_index=0
if len(tables) > table_index:
    specific_table = tables[table_index]
else:
    print('table index not found')
for i in specific_table.find_all('th'):
    exports_heading.append(i.text.strip())
for i in specific_table.find_all('td'):
    exports_data.append(i.text.strip())
for i in range(len(exports_heading)):
    export_data_dict[exports_heading[i]]=exports_data[i::6]
exports=pd.DataFrame(export_data_dict)
print(exports.head())
web.quit()

  Rank State or Union Territory Exports in million US$ Share of total exports  \
0    1                  Gujarat                146,485                 33.55%
1    2              Maharashtra                 72,498                 16.60%
2    3               Tamil Nadu                 40,673                  9.32%
3    4                Karnataka                 27,884                  6.39%
4    5            Uttar Pradesh                 21,686                  4.97%

  Leading export good     Year
0  Petroleum products  2022/23
1   Engineering goods  2022/23
2   Engineering goods  2022/23
3  Petroleum products  2022/23
4    Electronic goods  2022/23

In [12]:
url_hdi="https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_Human_Development_Index"
web=wd.Chrome()
web.get(url_hdi)
content=bs(web.page_source,'html.parser')
tables=content.find_all('table', class_='wikitable')
hdi_data=[]
hdi_heading=[]
hdi_data_dict={}
table_index=0
if len(tables) > table_index:
    specific_table = tables[table_index]
else:
    print('table index not found')
for i in specific_table.find_all('th'):
    hdi_heading.append(i.text.strip())
for i in specific_table.find_all('td'):
    hdi_data.append(i.text.strip())
hdi_data.insert(38,'0.688')
hdi_data.insert(95,'0.597')
hdi_heading.remove('Very High Human Development')
hdi_heading.remove('Medium Human Development')
for i in range(len(hdi_heading)):
    hdi_data_dict[hdi_heading[i]]=hdi_data[i::3]
hdi=pd.DataFrame(hdi_data_dict)
print(hdi.head())
web.quit()

  Rank State/Union Territory HDI (2021)
0    1                Kerala      0.752
1    2                   Goa      0.751
2    3            Chandigarh      0.744
3    4                 Delhi      0.730
4    5            Puducherry      0.726

In [13]:
url_electricity="https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_households_having_electricity"
web=wd.Chrome()
web.get(url_electricity)
content=bs(web.page_source,'html.parser')
tables=content.find_all('table', class_='wikitable')
electricity_data=[]
electricity_heading=[]
electricity_data_dict={}
table_index=0
if len(tables) > table_index:
    specific_table = tables[table_index]
else:
    print('table index not found')
for i in specific_table.find_all('th'):
    electricity_heading.append(i.text.strip())
for i in specific_table.find_all('td'):
    electricity_data.append(i.text.strip())
for i in range(len(electricity_heading)):
    electricity_data_dict[electricity_heading[i]]=electricity_data[i::5]
electricity_=pd.DataFrame(electricity_data_dict)
print(electricity_.head())
web.quit()

  State or union territory  \
0                   Kerala
1              Lakshadweep
2                    Delhi
3                      Goa
4               Puducherry

  Households having electricity (%) April 2019 (as reported by states)[3]  \
0                                                100
1                                                100
2                                                100
3                                                100
4                                                100

  Households having electricity (%) 2016[2]  \
0                                     100.0
1                                      99.9
2                                      99.8
3                                      99.8
4                                      99.6

  Households having electricity (%) (Census 2011)[1]  \
0                                               99.4
1                                               99.7
2                                               99.1
3                                               96.9
4                                               97.7

  Households having electricity (%) (Census 2001)[1]
0                                               97.9
1                                               99.7
2                                               92.9
3                                               93.6
4                                               87.8

In [14]:
url_access_to_safe_water="https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_access_to_safe_drinking_water"
web=wd.Chrome()
web.get(url_access_to_safe_water)
content=bs(web.page_source,'html.parser')
tables=content.find_all('table', class_='wikitable')
water_data=[]
water_heading=[]
water_data_dict={}
table_index=0
if len(tables) > table_index:
    specific_table = tables[table_index]
else:
    print('table index not found')
for i in specific_table.find_all('th'):
    water_heading.append(i.text.strip())
for i in specific_table.find_all('td'):
    water_data.append(i.text.strip())
water_data.remove('** All India Average')
water_data.remove('85.5')
for i in range(len(water_heading)):
    water_data_dict[water_heading[i]]=water_data[i::3]
safe_watr=pd.DataFrame(water_data_dict)
print(safe_watr.head())
web.quit()

  Rank             State  \
0    1            Kerala
1    2     Uttar Pradesh
2    3             Bihar
3    4           Haryana
4    5  Himachal Pradesh

  Percentage of households with access to safe drinking water(2011)
0                                               97.6
1                                               95.1
2                                               94.0
3                                               93.8
4                                               93.7

In [15]:
gdp_22_23.to_csv('gdp_22_23.csv',index=False,encoding='utf-8')
gdp_decade.to_csv('gdp_decade.csv',index=False,encoding='utf-8')
litracy_rate.to_csv('litracy_rate.csv',index=False,encoding='utf-8')

In [16]:
unemployement_rate.to_csv('unemployement_rate.csv',index=False,encoding='utf-8')
abbrevations.to_csv('abbrevations.csv',index=False,encoding='utf-8')
exports.to_csv('exports.csv',index=False,encoding='utf-8')
hdi.to_csv('hdi.csv',index=False,encoding='utf-8')
safe_watr.to_csv('safe_water.csv',index=False,encoding='utf-8')
electricity_.to_csv('electricity.csv',index=False,encoding='utf-8')